### ISSUE TITLE
Question about computing uncertainty

### ISSUE THREAD

**Issue by TheMrguiller** [vaishwarya96/MAPLE-uncertainty-estimation#1]
Hi,

I am a PhD student conducting a literature review on uncertainty for a hypothesis I am developing. I came across your paper and have a few questions.

Your method is highly dependent on the embedding space of the initial model. Have you applied the same approach to different base models that were pre-trained in similar ways to analyze if the generated K labels are similar between them in the embedding space? Specifically, do most of the images cluster similarly?

Additionally, regarding the computation of uncertainty, you mentioned computing uncertainty for each cluster. I assume you use the cluster with the least uncertainty as a baseline to determine if an example is out-of-distribution (OOD). However, you did not specify a threshold or provide any proof, correct?

I am genuinely new to this area of model uncertainty and am trying to observe patterns in various approaches. If any of my questions seem rude, I apologize in advance.

Thank you for your time and assistance.

**Comment by vaishwarya96** [comment]
Hi, sorry for the delayed response. 

Regarding your queries, yes I tried to see the clusters generated by different pre-trained models. Of course, not all generate exactly the same clusters, but there were some clusters that were identified by the different pre-trained models, with common attributes. 
For OOD detection, no, I do not specify any threshold. The metrics used for evaluation here are AUROC and AUPR scores, which do not require any thresholds, but are computed over a range of thresholds. Moreover, the threshold choice is application dependent, and needs to be decided by the user.
I hope this answers your questions.
